name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows x64
    runs-on: windows-2022
    steps:
      - name: Clone Fritzing repo
        uses: actions/checkout@v3
        with:
          repository: fritzing/fritzing-app
          ref: 29c2cede3a0475ed770db1ee502fdebf6bf3a23d
          path: fritzing
      - name: Clone libgit2 repo
        uses: actions/checkout@v3
        with:
          repository: libgit2/libgit2
          path: libgit2
      - name: Install VS2017 Build Tools
        run: choco install visualstudio2017buildtools visualstudio2017-workload-vctools
      - name: Install Qt 5.12.7
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.7'
          arch: win64_msvc2017_64
          dir: C:\
      - name: Download boost libraries
        run: |
          powershell -c "Invoke-WebRequest -Uri 'https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.7z' -OutFile 'boost.7z'"
          7z x boost.7z
      - name: Build libgit2
        run: |
          cd libgit2
          mkdir build64
          cd build64
          cmake ..
          cmake --build . --config Release
      - name: Build Fritzing
        run: |
          cd fritzing
          tools/build-windows.bat 0.9.10
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fritzing-0.9.10
          path: fritzing/release64/*.zip
          if-no-files-found: error
